version: "3.8"
services:
  chatlord:
    build:
      context: .
    env_file:
      - .env-non-dev
    command: ["gunicorn", "app.main:app", "--workers", "2", "--worker-class", "uvicorn.workers.UvicornWorker", "--bind=0.0.0.0:8000"]
    ports:
      - 4546:8000

  bot:
    build: .
    env_file:
      - .env-non-dev
    restart: always
    command: "python bot/bot.py"